version: '3'

services:  
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql:delegated
      - ./Docker/mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --init-file /data/application/init.sql
    restart: always
  
  tomcat:
    container_name: tomcat
    build: 
      context: .
      dockerfile: ./Docker/tomcat/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_HOST}/${SPRING_DATASOURCE_TABLE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_PROTOCOL: ${SPRING_MAIL_PROTOCOL}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_AUTH_ENABLE: ${SPRING_MAIL_AUTH_ENABLE}
      SPRING_MAIL_SMTP_TTLS_ENABLE: ${SPRING_MAIL_SMTP_TTLS_ENABLE}
      SPRING_MAIL_FROM: ${SPRING_MAIL_FROM}
      JWT_SECRET: ${JWT_SECRET}
      SPOTIFY_API_CLIENT_ID: ${SPOTIFY_API_CLIENT_ID}
      SPOTIFY_API_CLIENT_SECRET: ${SPOTIFY_API_CLIENT_SECRET}
      SPOTIFY_API_CLIENT_REDIRECT: ${SPOTIFY_API_CLIENT_REDIRECT}
      CURRENCIES_API_USERNAME: ${CURRENCIES_API_USERNAME}
      CURRENCIES_API_PASSWORD: ${CURRENCIES_API_PASSWORD}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      
    depends_on:
      - mysql
    ports:
      - 8080:8080
    restart: always

  reactjs:
    container_name: dashboard_app
    build: 
      context: .
      dockerfile: ./Docker/reactjs/Dockerfile
    restart: always
    volumes:
      - ./dashboard_app:/var/www/dashboard
      - ./dashboard_app/node_modules:/var/www/dashboard/node_modules
    ports:
      - 3000:3000
    working_dir: /var/www/dashboard
    command: "npm start"

  maildev:
    container_name: maildev
    image: maildev/maildev
    restart: always
    ports:
      - 1080:1080
      - 1025:1025

  phpmyadmin:
    container_name: pma
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    restart: always